<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("description", "Каталог товаров крупнейшего производителя стабилизаторов полимеров в России \"Ставропольской химической компании\". Цены от производителя, разработка продукта по индивидуальному ТЗ заказчика. Подробности можно узнать по телефону: +7 8652 23-90-23");
$APPLICATION->SetPageProperty("title", "Каталог продукции - Ставропольская химическая компания");
$APPLICATION->SetTitle("Каталог");
?>
<?$APPLICATION->IncludeComponent("bitrix:catalog", "custom-catalog", Array(
	"IBLOCK_ID" => "42",	// Инфоблок
		"IBLOCK_TYPE" => "aspro_allcorp3_catalog",	// Тип инфоблока
		"COMPONENT_TEMPLATE" => "main",
		"SECTIONS_TYPE_VIEW" => "FROM_MODULE",	// Шаблон страницы блока списка разделов
		"SECTION_TYPE_VIEW" => "FROM_MODULE",	// Шаблон страницы блока списка подразделов
		"SECTION_ELEMENTS_TYPE_VIEW" => "FROM_MODULE",	// Шаблон страницы блока списка элементов
		"ELEMENTS_PRICE_TYPE_VIEW" => "FROM_MODULE",	// Шаблон вывода элементов таблицей
		"ELEMENTS_LIST_TYPE_VIEW" => "FROM_MODULE",	// Шаблон вывода элементов списком
		"ELEMENTS_TABLE_TYPE_VIEW" => "FROM_MODULE",	// Шаблон вывода элементов плиткой
		"ELEMENT_TYPE_VIEW" => "FROM_MODULE",	// Шаблон страницы блока детальной страницы
		"ADD_PICT_PROP" => "PHOTOS",	// Дополнительная картинка основного товара
		"USER_CONSENT" => "N",	// Запрашивать согласие
		"USER_CONSENT_ID" => "0",	// Соглашение
		"USER_CONSENT_IS_CHECKED" => "Y",	// Галка по умолчанию проставлена
		"USER_CONSENT_IS_LOADED" => "N",	// Загружать текст сразу
		"SEF_MODE" => "Y",	// Включить поддержку ЧПУ
		"AJAX_MODE" => "N",	// Включить режим AJAX
		"AJAX_OPTION_JUMP" => "N",	// Включить прокрутку к началу компонента
		"AJAX_OPTION_STYLE" => "Y",	// Включить подгрузку стилей
		"AJAX_OPTION_HISTORY" => "N",	// Включить эмуляцию навигации браузера
		"AJAX_OPTION_ADDITIONAL" => "",	// Дополнительный идентификатор
		"CACHE_TYPE" => "A",	// Тип кеширования
		"CACHE_TIME" => "36000000",	// Время кеширования (сек.)
		"CACHE_FILTER" => "Y",	// Кешировать при установленном фильтре
		"CACHE_GROUPS" => "Y",	// Учитывать права доступа
		"USE_MAIN_ELEMENT_SECTION" => "N",	// Использовать основной раздел для показа элемента
		"DETAIL_STRICT_SECTION_CHECK" => "N",	// Строгая проверка раздела для детального показа элемента
		"SET_LAST_MODIFIED" => "N",	// Устанавливать в заголовках ответа время модификации страницы
		"SET_TITLE" => "Y",	// Устанавливать заголовок страницы
		"ADD_SECTIONS_CHAIN" => "Y",	// Включать раздел в цепочку навигации
		"ADD_ELEMENT_CHAIN" => "Y",	// Включать название элемента в цепочку навигации
		"SHOW_GALLERY" => "Y",
		"MAX_GALLERY_ITEMS" => "5",
		"SHOW_HINTS" => "Y",	// Показывать подсказки у свойств
		"COMPOSITE_FRAME_MODE" => "A",	// Голосование шаблона компонента по умолчанию
		"COMPOSITE_FRAME_TYPE" => "AUTO",	// Содержимое компонента
		"USE_FILTER" => "N",	// Показывать фильтр
		"ACTION_VARIABLE" => "action",	// Название переменной, в которой передается действие
		"PRODUCT_ID_VARIABLE" => "id",	// Название переменной, в которой передается код товара для покупки
		"USE_COMPARE" => "Y",	// Разрешить сравнение товаров
		"PRICE_CODE" => "",	// Тип цены
		"USE_PRICE_COUNT" => "N",	// Использовать вывод цен с диапазонами
		"SHOW_PRICE_COUNT" => "1",	// Выводить цены для количества
		"PRICE_VAT_INCLUDE" => "Y",	// Включать НДС в цену
		"PRICE_VAT_SHOW_VALUE" => "N",	// Отображать значение НДС
		"BASKET_URL" => "/personal/basket.php",	// URL, ведущий на страницу с корзиной покупателя
		"USE_PRODUCT_QUANTITY" => "N",	// Разрешить указание количества товара
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",	// Название переменной, в которой передается количество товара
		"ADD_PROPERTIES_TO_BASKET" => "Y",	// Добавлять в корзину свойства товаров и предложений
		"PRODUCT_PROPS_VARIABLE" => "prop",	// Название переменной, в которой передаются характеристики товара
		"PARTIAL_PRODUCT_PROPERTIES" => "N",	// Разрешить добавлять в корзину товары, у которых заполнены не все характеристики
		"SHOW_TOP_ELEMENTS" => "N",	// Выводить топ элементов
		"TOP_ELEMENT_COUNT" => "9",
		"TOP_LINE_ELEMENT_COUNT" => "3",
		"TOP_ELEMENT_SORT_FIELD" => "sort",
		"TOP_ELEMENT_SORT_ORDER" => "asc",
		"TOP_ELEMENT_SORT_FIELD2" => "id",
		"TOP_ELEMENT_SORT_ORDER2" => "desc",
		"SECTION_TOP_BLOCK_TITLE" => "Лучшие предложения",	// Заголовок блока
		"SECTION_COUNT_ELEMENTS" => "Y",	// Показывать количество элементов в разделе
		"SECTION_TOP_DEPTH" => "2",	// Максимальная отображаемая глубина разделов
		"SECTIONS_LIST_PREVIEW_DESCRIPTION" => "Y",	// Показывать описание разделов
		"SHOW_CHILD_SECTIONS" => "Y",	// Показывать вложенные подразделы
		"PAGE_ELEMENT_COUNT" => "10",	// Количество элементов на странице
		"LINE_ELEMENT_COUNT" => "3",	// Количество элементов, выводимых в одной строке таблицы
		"ELEMENT_SORT_FIELD" => "sort",	// По какому полю сортируем товары в разделе
		"ELEMENT_SORT_ORDER" => "asc",	// Порядок сортировки товаров в разделе
		"ELEMENT_SORT_FIELD2" => "id",	// Поле для второй сортировки товаров в разделе
		"ELEMENT_SORT_ORDER2" => "desc",	// Порядок второй сортировки товаров в разделе
		"INCLUDE_SUBSECTIONS" => "Y",	// Показывать элементы подразделов раздела
		"LIST_META_KEYWORDS" => "-",	// Установить ключевые слова страницы из свойства раздела
		"LIST_META_DESCRIPTION" => "-",	// Установить описание страницы из свойства раздела
		"LIST_BROWSER_TITLE" => "-",	// Установить заголовок окна браузера из свойства раздела
		"SECTION_BACKGROUND_IMAGE" => "-",	// Установить фоновую картинку для шаблона из свойства
		"LANDING_IBLOCK_ID" => "43",	// ID инфоблока посадочных страниц
		"LANDING_TIZER_IBLOCK_ID" => "1",	// ID инфоблока с тизерами в посадочных страницах
		"LANDING_SECTION_COUNT" => "20",	// Общее количество связанных посадочных страниц
		"LANDING_SECTION_COUNT_VISIBLE" => "3",	// Отображаемое количество связанных посадочных страниц
		"SORT_PROP" => array(	// Доступные поля для сортировки
			0 => "name",
			1 => "sort",
			2 => "FILTER_PRICE",
		),
		"COMPARE_NAME" => "CATALOG_COMPARE_LIST",	// Уникальное имя для списка сравнения
		"COMPARE_PROPERTY_CODE" => array(
			0 => "STATUS",
			1 => "ARTICLE",
			2 => "BRAND",
			3 => "GRUZ",
			4 => "GRUZ_STRELI",
			5 => "DLINA",
		),
		"SORT_PROP_DEFAULT" => "sort",	// Сортировка по умолчанию
		"SORT_DIRECTION" => "desc",	// Направление сортировки
		"VIEW_TYPE" => "table",	// Показывать товары в разделе по умолчанию
		"SECTION_DISPLAY_PROPERTY" => "UF_VIEWTYPE",	// Свойство раздела с шаблоном по умолчанию
		"SHOW_SECTION_DESC" => "Y",	// Показывать описание текущего раздела в списке элементов
		"SECTION_LIST_PREVIEW_DESCRIPTION" => "Y",	// Показывать описание подразделов
		"SHOW_LANDINGS" => "Y",	// Отображать блок "Популярные категории"
		"SECTION_LIST_DISPLAY_TYPE" => "3",	// Тип списка
		"OPT_BUY" => "Y",	// Оптовая покупка в табличном варианте
		"SHOW_ONE_CLINK_BUY" => "Y",
		"SECTION_ITEM_LIST_OFFSET_CATALOG" => "Y",
		"SECTION_ITEM_LIST_IMG_CORNER" => "N",
		"SECTION_ITEM_LIST_TEXT_CENTER" => "N",
		"DETAIL_META_KEYWORDS" => "-",	// Установить ключевые слова страницы из свойства
		"DETAIL_META_DESCRIPTION" => "-",	// Установить описание страницы из свойства
		"DETAIL_BROWSER_TITLE" => "-",	// Установить заголовок окна браузера из свойства
		"DETAIL_SET_CANONICAL_URL" => "N",	// Устанавливать канонический URL
		"SECTION_ID_VARIABLE" => "SECTION_ID",	// Название переменной, в которой передается код группы
		"DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",	// Использовать код группы из переменной, если не задан раздел элемента
		"DETAIL_BACKGROUND_IMAGE" => "-",	// Установить фоновую картинку для шаблона из свойства
		"SHOW_DEACTIVATED" => "N",	// Показывать деактивированные товары
		"T_DESC" => "",	// Альтернативный заголовок "Описание"
		"T_CHAR" => "",	// Альтернативный заголовок "Характеристики"
		"SHOW_BIG_GALLERY" => "Y",	// Отображать фотогалерею
		"T_BIG_GALLERY" => "",	// Альтернативный заголовок "Фотогалерея"
		"BIG_GALLERY_PROP_CODE" => "GALLEY_BIG",	// Свойство "Фотогалерея"
		"TYPE_BIG_GALLERY" => "BIG",	// Тип фотогалереи
		"T_VIDEO" => "",	// Альтернативный заголовок "Видео"
		"T_DOCS" => "",	// Альтернативный заголовок "Документы"
		"DOCS_PROP_CODE" => "DOCUMENTS",	// Свойство "Документы"
		"T_FAQ" => "",	// Альтернативный заголовок "Вопрос-ответ"
		"T_REVIEWS" => "",	// Альтернативный заголовок "Отзывы"
		"T_VACANCY" => "",	// Альтернативный заголовок "Вакансии"
		"T_STAFF" => "",	// Альтернативный заголовок "Сотрудники"
		"T_SALE" => "",	// Альтернативный заголовок "Акции"
		"T_NEWS" => "",	// Альтернативный заголовок "Новости"
		"T_ARTICLES" => "",	// Альтернативный заголовок "Статьи"
		"T_SERVICES" => "",	// Альтернативный заголовок "Услуги"
		"T_PROJECTS" => "",	// Альтернативный заголовок "Проекты"
		"T_PARTNERS" => "",	// Альтернативный заголовок "Партнеры"
		"T_GOODS" => "Вам может понравиться",	// Альтернативный заголовок "Товары"
		"SHOW_BUY" => "N",	// Отображать таб "Как купить"
		"T_BUY" => "",
		"SHOW_PAYMENT" => "N",	// Отображать таб "Оплата"
		"T_PAYMENT" => "",
		"SHOW_DELIVERY" => "N",	// Отображать таб "Доставка"
		"T_DELIVERY" => "",
		"SHOW_DOPS" => "N",	// Отображать таб "Дополнительно"
		"T_DOPS" => "",
		"DETAIL_USE_COMMENTS" => "N",	// Включить отзывы
		"SHOW_ASK_BLOCK" => "Y",	// Показывать блок "Задать вопрос"
		"ASK_FORM_ID" => "",	// ID формы "Задать вопрос"
		"PROPERTIES_DISPLAY_TYPE" => "TABLE",	// Показывать свойства
		"VISIBLE_PROP_COUNT" => "6",	// Количество отображаемых характеристик сверху
		"LINKED_ELEMENT_TAB_SORT_FIELD" => "sort",	// По какому полю сортируем связанные товары
		"LINKED_ELEMENT_TAB_SORT_ORDER" => "asc",	// Порядок сортировки связанные товары
		"LINKED_ELEMENT_TAB_SORT_FIELD2" => "id",	// Поле для второй сортировки связанные товары
		"LINKED_ELEMENT_TAB_SORT_ORDER2" => "desc",	// Порядок второй сортировки связанные товары
		"USE_SHARE" => "Y",	// Показывать ссылки на соцсети
		"LINK_IBLOCK_TYPE" => "",	// Тип инфоблока, элементы которого связаны с текущим элементом
		"LINK_IBLOCK_ID" => "",	// ID инфоблока, элементы которого связаны с текущим элементом
		"LINK_PROPERTY_SID" => "",	// Свойство, в котором хранится связь
		"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",	// URL на страницу, где будет показан список связанных элементов
		"USE_STORE" => "N",	// Показывать блок "Количество товара на складе"
		"PAGER_TEMPLATE" => "main",	// Шаблон постраничной навигации
		"DISPLAY_TOP_PAGER" => "N",	// Выводить над списком
		"DISPLAY_BOTTOM_PAGER" => "Y",	// Выводить под списком
		"PAGER_TITLE" => "Товары",	// Название категорий
		"PAGER_SHOW_ALWAYS" => "N",	// Выводить всегда
		"PAGER_DESC_NUMBERING" => "N",	// Использовать обратную навигацию
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",	// Время кеширования страниц для обратной навигации
		"PAGER_SHOW_ALL" => "N",	// Показывать ссылку "Все"
		"PAGER_BASE_LINK_ENABLE" => "N",	// Включить обработку ссылок
		"SET_STATUS_404" => "Y",	// Устанавливать статус 404
		"SHOW_404" => "Y",	// Показ специальной страницы
		"MESSAGE_404" => "",
		"COMPATIBLE_MODE" => "Y",	// Включить режим совместимости
		"USE_ELEMENT_COUNTER" => "Y",	// Использовать счетчик просмотров
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",	// Не подключать js-библиотеки в компоненте
		"SEF_FOLDER" => "/product/",	// Каталог ЧПУ (относительно корня сайта)
		"FILE_404" => "",	// Страница для показа (по умолчанию /404.php)
		"DETAIL_BLOG_USE" => "Y",
		"DETAIL_BLOG_URL" => "catalog_comments",
		"COMMENTS_COUNT" => "5",
		"DETAIL_BLOG_TITLE" => "Комментарии",
		"DETAIL_BLOG_EMAIL_NOTIFY" => "N",
		"DETAIL_VK_USE" => "Y",
		"DETAIL_VK_TITLE" => "ВКонтакте",
		"DETAIL_VK_API_ID" => "API_ID",
		"DETAIL_FB_USE" => "Y",
		"DETAIL_FB_TITLE" => "Facebook",
		"DETAIL_FB_APP_ID" => "APP_ID",
		"DETAIL_BLOCKS_ORDER" => "tabs,sku,sale,big_gallery,services,projects,news,articles,staff,partners,vacancy,goods,comments",	// Порядок отображения блоков
		"DETAIL_BLOCKS_TAB_ORDER" => "desc,char,tariffs,video,docs,faq,reviews,buy,payment,delivery,dops,complects",	// Порядок отображения табов
		"DETAIL_BLOCKS_ALL_ORDER" => "sale,desc,char,reviews,big_gallery,video,sku,tariffs,services,projects,news,articles,docs,staff,faq,partners,vacancy,goods,buy,payment,delivery,dops,comments",
		"USE_DETAIL_TABS" => "FROM_MODULE",	// Вид описания на детальной странице
		"PRODUCT_PROPERTIES" => "",
		"TOP_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "STATUS",
			1 => "LINK_SKU",
			2 => "ARTICLE",
			3 => "FORM_QUESTION",
			4 => "PRICE",
			5 => "FORM_ORDER",
			6 => "PRICE_CURRENCY",
			7 => "PRICEOLD",
			8 => "ECONOMY",
			9 => "FILTER_PRICE",
			10 => "DATE_COUNTER",
			11 => "HIT",
			12 => "BEST_ITEM",
			13 => "BRAND",
			14 => "DEPTH",
			15 => "GRUZ_STRELI",
			16 => "GRUZ",
			17 => "DLINA_STRELI",
			18 => "VOLUME",
			19 => "RECOMMEND",
			20 => "SPEED",
			21 => "WIDTH_PROHOD",
			22 => "WIDTH_PROEZD",
			23 => "",
		),
		"DETAIL_PROPERTY_CODE" => array(
			0 => "BLOG_POST_ID",
			1 => "POPUP_VIDEO",
			2 => "BLOG_COMMENTS_CNT",
			3 => "SHOW_ON_INDEX_PAGE",
			4 => "LINK_REGION",
			5 => "STATUS",
			6 => "LINK_SKU",
			7 => "ARTICLE",
			8 => "FORM_QUESTION",
			9 => "PRICE",
			10 => "FORM_ORDER",
			11 => "PRICE_CURRENCY",
			12 => "PRICEOLD",
			13 => "ECONOMY",
			14 => "FILTER_PRICE",
			15 => "BNR_TOP",
			16 => "DATE_COUNTER",
			17 => "INCLUDE_TEXT",
			18 => "VIDEO",
			19 => "HIT",
			20 => "VIDEO_IFRAME",
			21 => "BEST_ITEM",
			22 => "LINK_STUDY",
			23 => "LINK_PARTNERS",
			24 => "LINK_PROJECTS",
			25 => "LINK_STAFF",
			26 => "LINK_ARTICLES",
			27 => "BRAND",
			28 => "LINK_TARIF",
			29 => "LINK_TIZERS",
			30 => "LINK_VACANCY",
			31 => "LINK_REVIEWS",
			32 => "LINK_NEWS",
			33 => "LINK_SERVICES",
			34 => "LINK_FAQ",
			35 => "LINK_SALE",
			36 => "LINK_GOODS_FILTER",
			37 => "LINK_GOODS",
			38 => "SUPPLIED",
			39 => "AGE",
			40 => "KARTOPR",
			41 => "HEIGHT",
			42 => "DEPTH",
			43 => "DEEP",
			44 => "GRUZ_STRELI",
			45 => "GRUZ",
			46 => "DIAGONAL",
			47 => "DLINA_STRELI",
			48 => "DLINA",
			49 => "CATEGORY",
			50 => "CLASS",
			51 => "CLIMAT_CLASS",
			52 => "KOL_FORMULA",
			53 => "USERS",
			54 => "EXTENSION",
			55 => "MARK_STEEL",
			56 => "MASS",
			57 => "MODEL",
			58 => "POWER",
			59 => "UPDATES",
			60 => "VOLUME",
			61 => "SIZE",
			62 => "PLACE",
			63 => "RESOLUTION",
			64 => "LIGHTS_LOCATION",
			65 => "RECOMMEND",
			66 => "SERIES",
			67 => "SPEED",
			68 => "DURATION",
			69 => "PROIZVODSTVO",
			70 => "TEMPERATURE",
			71 => "TYPE",
			72 => "TYPE_TUR",
			73 => "THICKNESS",
			74 => "MARK",
			75 => "INCREASE",
			76 => "COLOR",
			77 => "FREQUENCY",
			78 => "FREQUENCE",
			79 => "WIDTH_PROHOD",
			80 => "WIDTH_PROEZD",
			81 => "WIDTH",
			82 => "LANGUAGES",
			83 => "CODE_TEXT",
			84 => "",
			"EDITION_1C","LINK_COMPLECT","DEMO_URL","MORE_PHOTO",
		),
		"SHOW_LIST_TYPE_SECTION" => "Y",	// Отображать переключение видов отображения товаров, если установлен вид отображения у конкретного раздела
		"SKU_IBLOCK_ID" => "20",	// Инфоблок торговых предложений
		"SKU_TREE_PROPS" => array(	// Свойства отбора торговых предложений
			0 => "COLOR",
			1 => "DIAMETER",
			2 => "DLINA",
			3 => "VYLET_STRELY",
			4 => "THICKNESS_STEEL",
			5 => "WIDTH",
		),
		"T_SKU" => "",	// Альтернативный заголовок "Цены"
		"SKU_PROPERTY_CODE" => array(	// Отображаемые свойства торговых предложений
			0 => "FORM_ORDER",
			1 => "STATUS",
			2 => "ARTICLE",
			3 => "PRICE_CURRENCY",
			4 => "PRICE",
			5 => "PRICEOLD",
			6 => "ECONOMY",
			7 => "COLOR",
			8 => "GOST",
			9 => "DLINA",
			10 => "VYLET_STRELY",
			11 => "MARK_STEEL",
			12 => "WIDTH",
		),
		"SKU_SORT_FIELD" => "sort",	// Поле для первой сортировки торговых предложений
		"SKU_SORT_ORDER" => "asc",	// Порядок для первой сортировки торговых предложений
		"SKU_SORT_FIELD2" => "name",	// Поле для второй сортировки торговых предложений
		"SKU_SORT_ORDER2" => "asc",	// Порядок для второй сортировки торговых предложений
		"T_TARIFFS" => "",	// Альтернативный заголовок "Тарифы"
		"SALE_STIKER" => "-",	// Свойство со стикером акций
		"USE_REVIEW" => "N",	// Разрешить отзывы
		"COMPARE_FIELD_CODE" => array(	// Поля
			0 => "",
			1 => "",
		),
		"COMPARE_ELEMENT_SORT_FIELD" => "sort",	// По какому полю сортируем элементы
		"COMPARE_ELEMENT_SORT_ORDER" => "asc",	// Порядок сортировки элементов
		"DISPLAY_ELEMENT_SELECT_BOX" => "N",	// Выводить список элементов инфоблока
		"SHOW_SKU_DESCRIPTION" => "N",	// Отображать описание для каждого торгового предложения
		"SEF_URL_TEMPLATES" => array(
			"sections" => "",
			"section" => "#SECTION_CODE_PATH#/",
			"element" => "#SECTION_CODE_PATH#/#ELEMENT_CODE#/",
			"compare" => "compare.php?action=#ACTION_CODE#",
			"smart_filter" => "#SECTION_CODE_PATH#/filter/#SMART_FILTER_PATH#/apply/",
		),
		"VARIABLE_ALIASES" => array(
			"compare" => array(
				"ACTION_CODE" => "action",
			),
		)
	),
	false
);?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>